import fs from "fs";
import path from "path";
import { withBasePath } from "@/lib/basePath";

const GALLERY_DIR = path.join(process.cwd(), "public/images/gallery");
const VALID_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".webp"]);

export type GalleryImage = {
  src: string;
  alt: string;
};

function toAltText(filename: string): string {
  const base = filename.replace(path.extname(filename), "");
  const looksAutoGenerated = /^(img|mvimg|whatsapp image|\d+)/i.test(base);
  if (looksAutoGenerated) return "ALyf2Ride ride photo";

  return base
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

export function getGalleryImages(): GalleryImage[] {
  let files: string[] = [];
  try {
    files = fs.readdirSync(GALLERY_DIR);
  } catch {
    return [];
  }

  return files
    .filter((file) => VALID_EXTENSIONS.has(path.extname(file).toLowerCase()))
    .sort()
    .map((file) => ({
      src: withBasePath(`/images/gallery/${encodeURIComponent(file)}`),
      alt: toAltText(file),
    }));
}
